// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsayb6KcpiCCYeB7Bh4O2MZWgiXyDHP74',
    appId: '1:205916219460:web:8fe2c43857b3d1670bf411',
    messagingSenderId: '205916219460',
    projectId: 'fav-places-4b3cd',
    authDomain: 'fav-places-4b3cd.firebaseapp.com',
    storageBucket: 'fav-places-4b3cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz0QkmoztERvAGIFus1uH4CdtioKJRFnw',
    appId: '1:205916219460:android:54c1d7c23a667c460bf411',
    messagingSenderId: '205916219460',
    projectId: 'fav-places-4b3cd',
    storageBucket: 'fav-places-4b3cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-gzfp2IsoS_-Ng0b8W9uJDa2xyWwM3as',
    appId: '1:205916219460:ios:0ac20708c6eadb4a0bf411',
    messagingSenderId: '205916219460',
    projectId: 'fav-places-4b3cd',
    storageBucket: 'fav-places-4b3cd.appspot.com',
    iosBundleId: 'com.example.flutterDashboardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-gzfp2IsoS_-Ng0b8W9uJDa2xyWwM3as',
    appId: '1:205916219460:ios:0ac20708c6eadb4a0bf411',
    messagingSenderId: '205916219460',
    projectId: 'fav-places-4b3cd',
    storageBucket: 'fav-places-4b3cd.appspot.com',
    iosBundleId: 'com.example.flutterDashboardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsayb6KcpiCCYeB7Bh4O2MZWgiXyDHP74',
    appId: '1:205916219460:web:464bcc95f22f9e8e0bf411',
    messagingSenderId: '205916219460',
    projectId: 'fav-places-4b3cd',
    authDomain: 'fav-places-4b3cd.firebaseapp.com',
    storageBucket: 'fav-places-4b3cd.appspot.com',
  );

}